// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flatland/protobuf/extensions.proto

package flatland.protobuf;

public final class Extensions {
  private Extensions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(flatland.protobuf.Extensions.set);
    registry.add(flatland.protobuf.Extensions.map);
    registry.add(flatland.protobuf.Extensions.mapBy);
    registry.add(flatland.protobuf.Extensions.counter);
    registry.add(flatland.protobuf.Extensions.succession);
    registry.add(flatland.protobuf.Extensions.mapDeleted);
    registry.add(flatland.protobuf.Extensions.mapExists);
    registry.add(flatland.protobuf.Extensions.meta);
    registry.add(flatland.protobuf.Extensions.nullable);
    registry.add(flatland.protobuf.Extensions.nullString);
    registry.add(flatland.protobuf.Extensions.nullInt);
    registry.add(flatland.protobuf.Extensions.nullLong);
    registry.add(flatland.protobuf.Extensions.nullFloat);
    registry.add(flatland.protobuf.Extensions.nullDouble);
    registry.add(flatland.protobuf.Extensions.nullEnum);
  }
  public static final int SET_FIELD_NUMBER = 52001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> set = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int MAP_FIELD_NUMBER = 52002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> map = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int MAP_BY_FIELD_NUMBER = 52003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> mapBy = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int COUNTER_FIELD_NUMBER = 52004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> counter = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int SUCCESSION_FIELD_NUMBER = 52005;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> succession = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int MAP_DELETED_FIELD_NUMBER = 52006;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> mapDeleted = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int MAP_EXISTS_FIELD_NUMBER = 52007;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> mapExists = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int META_FIELD_NUMBER = 52010;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> meta = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int NULLABLE_FIELD_NUMBER = 52020;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> nullable = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int NULL_STRING_FIELD_NUMBER = 52021;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> nullString = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int NULL_INT_FIELD_NUMBER = 52022;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> nullInt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int NULL_LONG_FIELD_NUMBER = 52023;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Long> nullLong = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  public static final int NULL_FLOAT_FIELD_NUMBER = 52024;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Float> nullFloat = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Float.class,
        null);
  public static final int NULL_DOUBLE_FIELD_NUMBER = 52025;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Double> nullDouble = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Double.class,
        null);
  public static final int NULL_ENUM_FIELD_NUMBER = 52026;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> nullEnum = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"flatland/protobuf/extensions.proto\032 go" +
      "ogle/protobuf/descriptor.proto:,\n\003set\022\035." +
      "google.protobuf.FieldOptions\030\241\226\003 \001(\010:,\n\003" +
      "map\022\035.google.protobuf.FieldOptions\030\242\226\003 \001" +
      "(\010:/\n\006map_by\022\035.google.protobuf.FieldOpti" +
      "ons\030\243\226\003 \001(\t:0\n\007counter\022\035.google.protobuf" +
      ".FieldOptions\030\244\226\003 \001(\010:3\n\nsuccession\022\035.go" +
      "ogle.protobuf.FieldOptions\030\245\226\003 \001(\010:4\n\013ma" +
      "p_deleted\022\035.google.protobuf.FieldOptions" +
      "\030\246\226\003 \001(\t:3\n\nmap_exists\022\035.google.protobuf",
      ".FieldOptions\030\247\226\003 \001(\t:-\n\004meta\022\035.google.p" +
      "rotobuf.FieldOptions\030\252\226\003 \001(\t:1\n\010nullable" +
      "\022\035.google.protobuf.FieldOptions\030\264\226\003 \001(\010:" +
      "4\n\013null_string\022\035.google.protobuf.FieldOp" +
      "tions\030\265\226\003 \001(\t:1\n\010null_int\022\035.google.proto" +
      "buf.FieldOptions\030\266\226\003 \001(\021:2\n\tnull_long\022\035." +
      "google.protobuf.FieldOptions\030\267\226\003 \001(\022:3\n\n" +
      "null_float\022\035.google.protobuf.FieldOption" +
      "s\030\270\226\003 \001(\002:4\n\013null_double\022\035.google.protob" +
      "uf.FieldOptions\030\271\226\003 \001(\001:2\n\tnull_enum\022\035.g",
      "oogle.protobuf.FieldOptions\030\272\226\003 \001(\rB\037\n\021f" +
      "latland.protobufB\nExtensions"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    set.internalInit(descriptor.getExtensions().get(0));
    map.internalInit(descriptor.getExtensions().get(1));
    mapBy.internalInit(descriptor.getExtensions().get(2));
    counter.internalInit(descriptor.getExtensions().get(3));
    succession.internalInit(descriptor.getExtensions().get(4));
    mapDeleted.internalInit(descriptor.getExtensions().get(5));
    mapExists.internalInit(descriptor.getExtensions().get(6));
    meta.internalInit(descriptor.getExtensions().get(7));
    nullable.internalInit(descriptor.getExtensions().get(8));
    nullString.internalInit(descriptor.getExtensions().get(9));
    nullInt.internalInit(descriptor.getExtensions().get(10));
    nullLong.internalInit(descriptor.getExtensions().get(11));
    nullFloat.internalInit(descriptor.getExtensions().get(12));
    nullDouble.internalInit(descriptor.getExtensions().get(13));
    nullEnum.internalInit(descriptor.getExtensions().get(14));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
