#!/bin/sh

if [ -L $0 ]; then
  FILE=`readlink $0`
else
  FILE=$0
fi
DIR=`dirname $FILE`
TMP_DIR="/tmp/protoclj-`date +%s`"
SRC_DIR=${2:-'.'}
CLASS_DIR=${2:-$SRC_DIR}

mkdir -p $TMP_DIR $SRC_DIR $CLASS_DIR
protoc $1 -I$DIR/../include -I. --java_out=$TMP_DIR
cp -Rf $TMP_DIR/ $SRC_DIR
javac -d $CLASS_DIR -cp $DIR/../var/java/clojure-protobuf.jar `find $TMP_DIR -name *.java`